project:
  type: website

website:
  title: "Jonathan Atyeo"
  navbar:
    right:
      - href: index.qmd
        text: HOME
      - href: posts.qmd
        text: POSTS
      - href: about.qmd
        text: ABOUT
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://code.com
  page-footer: 
    left: "test2"
    right:
      - icon: github
        href: https://github.com/
        
      

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

